### ISSUE TITLE
Validation framework does not compare all the possible combinations

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/pytesmo#185] opened 2020-05-15 12:02 UTC
e..g in the test in https://github.com/TUW-GEO/pytesmo/blob/master/tests/test_validation_framwork/test_validation.py#L416

We have 3 datasets `DS1`, `DS2` and `DS3` which are compared with this config:

```python
    process = Validation(
        datasets, 'DS1',
        temporal_matcher=temporal_matchers.BasicTemporalMatching(
            window=1 / 24.0).combinatory_matcher,
        scaling='lin_cdf_match',
        metrics_calculators={
            (3, 2): metrics_calculators.BasicMetrics(other_name='k1').calc_metrics})
```

But in the results the combination between `DS2` and `DS3` is missing.

@wpreimes @tracyscanlon was this ever an issue in QA4SM?

**Comment by wpreimes** [comment] 2020-05-15 12:49
Aren't the combinations supposed to be created only between the temporal reference and all other datasets? https://github.com/TUW-GEO/pytesmo/blob/63aa4602a0a69ebb958c8ed6ce87461efc49725b/pytesmo/validation_framework/temporal_matchers.py#L124

**Comment by wpreimes** [comment] 2020-05-15 12:51
In QA4SM this is actually what we do, so no matching between non-reference datasets.

**Comment by cpaulik** [comment] 2020-05-15 13:22
I think that depends on the `(n, k)` setting. if you run the framework with `(2, 2)` then you always get 2 datasets temporally matched to each other. But we run it with `(3, 2)` which according to the documentation should temporally match the 3 datasets and then give you all combinations of 2 datasets as the results.

Also in the test we get a dataframe like:

```
n_matched_data
{('DS1', 'DS2', 'DS3'):             (DS1, x)  (DS1, y)  (DS2, x)  (DS2, y)  (DS3, x)  (DS3, y)
2000-01-01         0       0.0       0.0       0.0       0.0       0.0

```

But do do it correctly you should temporally match all three and then calculate the basic metrics on the combinations. Otherwise you give an advantage to the `temporal reference` dataset.

**Comment by cpaulik** [comment] 2020-05-15 13:44
I guess this bug/misunderstanding is the reason for the metric calculators mixing metrics for 2 datasets and more?

@sebhahn same thing for the HSAF metrics I guess.

**Comment by wpreimes** [comment] 2020-05-15 13:47
Then I guess the combinations have to be created differntly https://github.com/TUW-GEO/pytesmo/blob/63aa4602a0a69ebb958c8ed6ce87461efc49725b/pytesmo/validation_framework/validation.py#L261-L263
because there the ref column is always used, and that one is fixed in the whole validation framework to the temp ref? https://github.com/TUW-GEO/pytesmo/blob/63aa4602a0a69ebb958c8ed6ce87461efc49725b/pytesmo/validation_framework/data_manager.py#L427-L429

**Comment by sebhahn** [comment] 2020-05-15 13:51
@cpaulik sorry, I cannot comment on this issue, because I'm using the metrics directly and not the framework around it

**Comment by cpaulik** [comment] 2020-05-15 14:09
> Then I guess the combinations have to be created differntly
> 
> https://github.com/TUW-GEO/pytesmo/blob/63aa4602a0a69ebb958c8ed6ce87461efc49725b/pytesmo/validation_framework/validation.py#L261-L263
> 
> because there the ref column is always used, and that one is fixed in the whole validation to the temp ref?
> 
> https://github.com/TUW-GEO/pytesmo/blob/63aa4602a0a69ebb958c8ed6ce87461efc49725b/pytesmo/validation_framework/data_manager.py#L427-L429

Yes I already have a fix for creating the combinations of the `dataset.column` matches. We can discuss in the MR that I will open.

I was just surprised that nobody had encountered this. But it seems people just worked around it.

**Comment by cpaulik** [comment] 2020-05-15 14:12
> @cpaulik sorry, I cannot comment on this issue, because I'm using the metrics directly and not the framework around it

That hurts a little :smile:

**Comment by awst-baum** [comment] 2020-05-15 14:15
@cpaulik If it consoles you a little: 70 users are using your framework through qa4sm ;)

**Comment by wpreimes** [comment] 2020-05-15 14:20
@cpaulik maybe you can use that one: https://github.com/TUW-GEO/pytesmo/blob/63aa4602a0a69ebb958c8ed6ce87461efc49725b/pytesmo/df_metrics.py#L43 guess we shouldn't have too many functions to create combinations of elements...

**Comment by cpaulik** [comment] 2020-05-15 14:59
> @cpaulik If it consoles you a little: 70 users are using your framework through qa4sm ;)

Thanks. That helps a bit.

@awst-baum have you been running the validations with settings like `(4, 4)` and `(3, 3)` for the metric calculators to get all of the datasets into the metric calculator at once?

**Comment by awst-baum** [comment] 2020-05-15 15:06
If I'm understanding this discussion correctly (not sure, tbh), then yes. See
https://github.com/awst-austria/qa4sm/blob/de40fc48c1d7b597472256757f44c6c47fcb0dd8/validator/validation/validation.py#L154:

`metrics_calculators={(ds_num, ds_num): metrics.calc_metrics}`

`ds_num` is the number of datasets and `metrics` is an instance of @wpreimes 's `IntercomparisonMetrics`. But in the end I just put into the webapp what Wolfi told me to :D

**Comment by cpaulik** [comment] 2020-05-20 10:07
Just opened https://github.com/TUW-GEO/pytesmo/pull/187 which should fix this. Especially if the webservice uses `(ds_num, ds_num)` then nothing should change there.

**Comment by wpreimes** [comment] 2020-05-25 12:46
by the way, the reason why we loaded all datasets into the metrics calculator before creating the combinations there was, because we wanted to use only observations that are available in ALL datasets at any time (so that the comparison is "fair", e.g. if one dataset has less observations under cold temperature conditions etc.). I guess we could add the option to `dropna()` somwhere else (after the temp. matching of all `n` series). Then we could use the metrics calculator as intended and use the functionality for the combinations from the validation framework (matching  `n` datasets, then already dropping timestamps where not all datasets have a value, then creating the k combinations and handling them to the metrics calc.). When I implemented this for QA4SM, I tried to keep all changes in the metrics calc and to not change any other parts of the validation framework.

**Comment by cpaulik** [comment] 2020-05-25 13:27
I understand. In the original design the idea was to keep the metric calculators quite dumb so you could mix and match them using the `(n, k)` syntax during the configuration. 

Because the metric calculator should only do that. 
For changing the temporal matching also using the `temporal_matcher` argument to provide a function which drops some columns of the dataframe could be an option.

**Comment by wpreimes** [comment] 2020-10-02 08:19
#187 is merged, therefore I'm closing this issue. I am aware that we should simplify the metrics calculators and let the validation framework create the data set combinations, I will open a new issue for that.

**Closed by wpreimes** 2020-10-02 08:19 UTC
